sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_4e798a0779bf_key -iv $encrypted_4e798a0779bf_iv -in service-account.json.enc -out service-account.json -d
  - curl http://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project multi-k8s-232108
  - gcloud config set compute/zone europe-west4-c
  - gcloud container clusters get-credentials standard-cluster-1
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t dreddko/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run dreddko/react-test npm run test -- --coverage

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master